# Numpy uppgifter

- Uppgift 1
- Uppgift 2
- Uppgift 3

In [25]:
# Uppgift 1 a)
import numpy as np

tal = np.arange(1,11)
print(tal) 

[ 1  2  3  4  5  6  7  8  9 10]


In [24]:
# Uppgift 1 b)
import numpy as np

tal = np.arange(-10, 11)
print(tal)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]


In [40]:
# Uppgift 2
import numpy as np

tal = np.array([1,2,3,4,5,6,7,8,9,10])
print(tal)
tal2 = tal*10
print(tal2)
tal3 = tal2*10
print(tal3)

[ 1  2  3  4  5  6  7  8  9 10]
[ 10  20  30  40  50  60  70  80  90 100]
[ 100  200  300  400  500  600  700  800  900 1000]


In [ ]:
# Uppgift 3
# Uppgift 2
import numpy as np

tal = np.array([1,2,3,4,5,6,7,8,9,10])
print(tal)
tal2 = tal*10
print(tal2)
tal3 = tal2*10
print(tal3)
